### ISSUE TITLE
iOS giving error when launching quick match in rtmp

### ISSUE THREAD

**Issue by Jessicardo** [playgameservices/ios-basic-samples#10]
I'm developing a real-time multiplayer game for Android an iOS with Google Play Game Services.

The GPG is implemented in the game as Google's documentation tells and this works well on Android. But on iOS, the game shows an error log (does not crash) when trying to automatch.

"2015-02-22 13:13:13.458 [RTMP] (Error) +[GPGRealTimeRoomMaker performPreCheck:checkDelegate:]:[main] Real-time multiplayer is not enabled for the game"

Note this error comes up when i call "[GPGRealTimeRoomMaker createRoomFromConfig:config];" or "[[GPGLauncherController sharedInstance] presentRealTimeWaitingRoomWithConfig:config];"

I have this setting enabled for the iOS linked app. I also have the certificates linked up. Signing in works well and I have fully implemented Google Play Game Services on the Android game, but on iOS i cannot proceed because of that error (the player is not found by the other 2 players on android devices"

for example if the app's name is TestGame with a bundle of com.a.b, I provided the bundle Id as com.a.b.TestGame. the .p12 (APNS) certificates are also using that bundle id.

I have done a lot of troubleshooting and debugging, but cannot figure this out. I was wondering if anyone else has encountered this issue before. I can provide more details if need be.

**Comment by ToddKerpelman** [comment]
When we've seen this in the past, it's usually been a caching issue. Have you tried deleting your iOS app and re-installing it?

**Comment by Jessicardo** [comment]
I have, but I can try again. Is the APNS certificate required to get this to work? I have it setup, but just wondering because when i turn on real time multiplayer on the console and then save it without a certificate, going back into the app details shows and error and turns off the switch. It also removes the client Id and then i have to delete the app on the google play developer console and link it again.

**Comment by ToddKerpelman** [comment]
You shouldn't need a certificate -- that's only for being notified if you receive an invite. But this whole "error and turning off the switch" thing seems like a problem. What error does it tell you, exactly?

**Comment by Jessicardo** [comment]
Something along the lines of "Error loading this page" This shows up in red on the linked app iOS detail page were you turn off/on the real time multiplayer settings. I can provide steps to reproduce later on tonight.

**Comment by Jessicardo** [comment]
I've gone through the basic samples and everything seems good on my end. The next step for me would be to provide screenshots of the iOS linked app in the google play developer console (while hiding sensitive info). That may help in debugging the issue.

**Comment by Jessicardo** [comment]
In the Steps to run the sample app, the final step reads "Go to your ButtonClicker-info.plist file and replace the GPGApplication value with the actual Application ID of your game." I looked at the source code on the project and don't see "GPGApplication" as a key in the p-list. Is this step required?.

**Comment by Jessicardo** [comment]
I was able to finally solve my initial issue, this issue can be closed now.

PROBLEM: I have a lobby screen which i call "[[GPGManager sharedInstance] signInWithClientID:GOOGLE_GAME_SERVICES_CLIENT_ID silently:NO];", and i also have a game screen that comes after the lobby screen which i call "[[GPGManager sharedInstance] signInWithClientID:GOOGLE_GAME_SERVICES_CLIENT_ID silently:NO];" again. What i had to do was replace the code in the game screen with a check if user signed in and if not call "[[GPPSignIn sharedInstance] authenticate];" instead!
It still crashes on an actual device like the sample app, but my initial issue is resolved.
