### ISSUE TITLE
using Game services and Firebase in my project

### ISSUE THREAD

**Issue by myflashlab** [playgameservices/ios-basic-samples#15]
This was very hard and confusing to find out but I finally figured out that current game services V5.1 is using [google_signin_sdk_2_4_0](https://developers.google.com/identity/sign-in/ios/sdk/google_signin_sdk_2_4_0.zip)

while the Firebase project is using the latest one. and if I upgrade to the latest version of Google signin, it throws many weird error messages and my app does not compile!

So, the question is: How can someone use GamesServices AND Firebase in a project? I hoped that using the latest google_signin_sdk would do the job, but it's not.

What are my options? Thanks for your advice in advance.

**Comment by claywilkinson** [comment]
Unfortunately, Google Play Game Services is deprecated on iOS: https://android-developers.googleblog.com/2017/04/focusing-our-google-play-games-services.html

So I recommend using Firebase along with GoogleSignIn SDK (latest version) and not use GPGS.
