### ISSUE TITLE
Access GIDGoogleUser Class

### ISSUE THREAD

**Issue by adrianha** [playgameservices/ios-basic-samples#2]
Hello,
Is there any solution to access GIDGoogleUser Class?
Since there are no props or methods related to that class.
I wanna get user profile such as email and name...

**Comment by adrianha** [comment]
hello @claywilkinson can you help me?

**Comment by gguuss** [comment]
After you have signed the user in using PGS, you should be able to use GIDSignin.sharedInstance to retrieve the user [just as is done in the Unity Plugin](https://github.com/playgameservices/play-games-plugin-for-unity/blob/36ee1c3edd4c5b764943a92bbd56f00073d9a021/source/PluginDev/Assets/Plugins/iOS/GPGSAppController.mm).

Note, that you need to configure the Sign-in button to fetch profile data before signing in the user unless you intend to use the ID token or access token to retrieve the profile data.
