### ISSUE TITLE
Not able to set turnBasedMatchDelegate

### ISSUE THREAD

**Issue by geopaulm** [playgameservices/ios-basic-samples#3]
I have used the code [GPGManager sharedInstance].turnBasedMatchDelegate = self at lot of places. Also I have implemented the interface "GPGTurnBasedMatchDelegate" but the method "- (void)didReceiveTurnBasedInviteForMatch:(GPGTurnBasedMatch *)match
                              participant:(GPGTurnBasedParticipant *)participant
                     fromPushNotification:(BOOL)fromPushNotification;" never gets fired. 
Am I missing something?
Rest everything works fine.
Also sometimes the above call get fired when there is a push notification.

**Comment by gguuss** [comment]
Closing old issue, I just tested the TBMP sample and can't reproduce this. Various changes may have fixed this already.

**Comment by esdebon** [comment]
I have the same problem:

```c
-(void) didReceiveTurnBasedInviteForMatch: (GPGTurnBasedMatch *) match
participant: (GPGTurnBasedParticipant *) participant
fromPushNotification: (BOOL) fromPushNotification; 
```
**NEVER GETS FIRED!!!**

I've placed in several places:
```c
  [GPGManager sharedInstance] .turnBasedMatchDelegate = self;
```

This is really sad, I guess like in the real-time multiplayer, google's people are only testing on the simulator, or on the iPhone's dad, this is not professional.

**I'm using Xcode 6.1 with Games SDK Version 3.1.1 tested on iPhone 5, iPod Touch 5 and iPad 3 Retina Display**
