### ISSUE TITLE
listRoomsWithMaxResults result is triggered twice

### ISSUE THREAD

**Issue by hansagames** [playgameservices/ios-basic-samples#3]
Hi.

I use this method

``` objc
[GPGRealTimeRoomMaker listRoomsWithMaxResults:50 completionHandler:^(NSArray *rooms, NSError *error) {
                if(error) {
                   /// error
                }
                else {
                    NSMutableArray *validRoomDataList = [NSMutableArray array];

                    for (GPGRealTimeRoomData *roomData in rooms) {

                        if (roomData.status == GPGRealTimeRoomStatusInviting) {
                            [validRoomDataList addObject:roomData];
                        }
                    }
                    [[GPGLauncherController sharedInstance] presentRealTimeInvitesWithRoomDataList:validRoomDataList];
                }
        }];
```

to show all invitations for current user, but **completionHandler** is called twice, once with invitations and once empty, so I get two windows.

I test on iPad 2 with iOS 9.2.1

Thank you.

**Comment by myflashlab** [comment]
Same issue here also. tested on iOS 9.3.1 and besides that, when I hit the `Accept` button, nothing happens! the `decline` button works fine though. any idea? Thanks.

**Comment by hansagames** [comment]
I use bool and set it true before I call this method and set it to false after first result to ignore second.

**Comment by myflashlab** [comment]
Yeah, actually I went with a similar solution. Thanks for your reply anyhow. Yet, considering that you are also working with invitations, I wonder if you faced similar problems with push notifications on iOS? https://github.com/playgameservices/ios-basic-samples/issues/7#issuecomment-218650914 just asking :)
