### ISSUE TITLE
push notification does not work!

### ISSUE THREAD

**Issue by myflashlab** [playgameservices/ios-basic-samples#7]
We're doing all the steps required for enabling push notification for invitations but `didReceiveRealTimeInviteForRoom` is never called and I have no idea where to look any more.

I do receive APNS token successfully I must add but when I send an invitation, no push notification is delivered to my app although I am able to see the waiting invitation in the built-in UI window.

I tested with development and production environments but none are working. and of course we are careful with the environment settings

``` objective-c
GPGPushNotificationEnvironment environment = GPGPushNotificationEnvironmentSandbox;
if(isBuildingForProduction) environment = GPGPushNotificationEnvironmentProduction;

[[GPGManager sharedInstance] registerDeviceToken:deviceToken forEnvironment:environment];
```

We would appreciate any help or guidelines?

**Comment by claywilkinson** [comment]
Unfortunately this is a known issue in the iOS SDK. https://developers.google.com/games/services/ios/knownIssues

I don't have a specific timeline for an update.  I'll make sure this issue gets updated when more information is known.

**Comment by myflashlab** [comment]
Thanks for the reply. However, by googling for the problem, I noticed that the problem is with the production mode and devs were not able to receive push notifications on the production mode only.

My problem is that I can't make it work even on the developer mode! Any ideas?
